# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'superble' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Messaging'

  # Pods for superble

  target 'superbleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'superble-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for superble-tvOS

  target 'superble-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
